### PR TITLE
Fix mypy precheck failures

### PR DESCRIPTION
**Pull request by benmoss**
### Description

The precommit hook is failing in https://github.com/conda/conda-lock/pull/626 (among other places) with these errors:

```
conda_lock/invoke_conda.py:197: error: Non-overlapping equality check (left operand type: "Channel", right operand type: "Literal['defaults']")  [comparison-overlap]
conda_lock/conda_solver.py:349: error: Non-overlapping equality check (left operand type: "Channel", right operand type: "Literal['defaults']")  [comparison-overlap]
```

I'm not a Python expert but I think the problem is we're comparing a `Channel` with a string, and equality isn't implemented for those two types. We could either just compare the `url` field or turn the `"defaults"` string into a channel, not sure which is preferred.

### CODE REVIEW

**Comment by maresb** [comment]
Thanks a lot @benmoss for taking initiative on this!!! (I had a very busy week.)

The msys2 stuff predates my involvement in conda-lock, so I needed to do a bit of research to understand what it's all about. I've added a test case to ensure that the newly-activated code is actually correct.

**Comment by maresb** [comment]
We should be able to cut a new release as soon as everything is confirmed green.
